Config = {}
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true' -- Use qb-target interactions (don't change this, go to your server.cfg and add `setr UseTarget true` to use this and just that from true to false or the other way around)

Config.Products = {
    ["weapon"] = {
        [1] = {
            name = "weapon_pistol_mk2",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_combatpistol",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weapon_appistol",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "weapon_pistol50",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "weapon_snspistol",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "weapon_heavypistol",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "weapon_vintagepistol",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "weapon_marksmanpistol",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "weapon_revolver",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "weapon_revolver_mk2",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "weapon_doubleaction",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "weapon_snspistol_mk2",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "weapon_microsmg",
            price = 3000,
            amount = 50,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "weapon_smg",
            price = 3000,
            amount = 50,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "weapon_smg_mk2",
            price = 3000,
            amount = 50,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "weapon_assaultsmg",
            price = 3000,
            amount = 50,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "weapon_combatpdw",
            price = 3000,
            amount = 50,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "weapon_machinepistol",
            price = 3000,
            amount = 50,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "weapon_minismg",
            price = 3000,
            amount = 50,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "weapon_pumpshotgun",
            price = 2500,
            amount = 50,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "weapon_sawnoffshotgun",
            price = 2500,
            amount = 50,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "weapon_assaultshotgun",
            price = 2500,
            amount = 50,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "weapon_bullpupshotgun",
            price = 2500,
            amount = 50,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "weapon_musket",
            price = 2500,
            amount = 50,
            info = {},
            type = "item",
            slot = 24,
        },
        [25] = {
            name = "weapon_heavyshotgun",
            price = 2500,
            amount = 50,
            info = {},
            type = "item",
            slot = 25,
        },
        [26] = {
            name = "weapon_dbshotgun",
            price = 2500,
            amount = 50,
            info = {},
            type = "item",
            slot = 26,
        },
        [27] = {
            name = "weapon_autoshotgun",
            price = 2500,
            amount = 50,
            info = {},
            type = "item",
            slot = 27,
        },
        [28] = {
            name = "weapon_pumpshotgun_mk2",
            price = 2500,
            amount = 50,
            info = {},
            type = "item",
            slot = 28,
        },
        [29] = {
            name = "weapon_assaultrifle",
            price = 5000,
            amount = 50,
            info = {},
            type = "item",
            slot = 29,
        },
        [30] = {
            name = "weapon_assaultrifle_mk2",
            price = 5000,
            amount = 50,
            info = {},
            type = "item",
            slot = 30,
        },
        [31] = {
            name = "weapon_carbinerifle",
            price = 5000,
            amount = 50,
            info = {},
            type = "item",
            slot = 31,
        },
        [32] = {
            name = "weapon_carbinerifle_mk2",
            price = 5000,
            amount = 50,
            info = {},
            type = "item",
            slot = 32,
        },
        [33] = {
            name = "weapon_advancedrifle",
            price = 5000,
            amount = 50,
            info = {},
            type = "item",
            slot = 33,
        },
        [34] = {
            name = "weapon_specialcarbine",
            price = 5000,
            amount = 50,
            info = {},
            type = "item",
            slot = 34,
        },
        [35] = {
            name = "weapon_bullpuprifle",
            price = 5000,
            amount = 50,
            info = {},
            type = "item",
            slot = 35,
        },
        [36] = {
            name = "weapon_compactrifle",
            price = 5000,
            amount = 50,
            info = {},
            type = "item",
            slot = 36,
        },
        [37] = {
            name = "weapon_specialcarbine_mk2",
            price = 1500000,
            amount = 50,
            info = {},
            type = "item",
            slot = 37,
        },
        [38] = {
            name = "weapon_bullpuprifle_mk2",
            price = 5000,
            amount = 50,
            info = {},
            type = "item",
            slot = 38,
        },
        [39] = {
            name = "weapon_mg",
            price = 10000,
            amount = 50,
            info = {},
            type = "item",
            slot = 39,
        },
        [40] = {
            name = "weapon_combatmg",
            price = 10000,
            amount = 50,
            info = {},
            type = "item",
            slot = 40,
        },
        [41] = {
            name = "weapon_combatmg_mk2",
            price = 10000,
            amount = 50,
            info = {},
            type = "item",
            slot = 41,
        },
        [42] = {
            name = "pistol_ammo",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 42,
        },
        [43] = {
            name = "smg_ammo",
            price = 80,
            amount = 50,
            info = {},
            type = "item",
            slot = 43,
        },
        [44] = {
            name = "shotgun_ammo",
            price = 40,
            amount = 50,
            info = {},
            type = "item",
            slot = 44,
        },
        [45] = {
            name = "rifle_ammo",
            price = 75,
            amount = 50,
            info = {},
            type = "item",
            slot = 45,
        },
        [46] = {
            name = "mg_ammo",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 46,
        },
    },
    ["weaponattachments"] = {
        [1] = {
            name = "pistol_defaultclip",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
       [2] = {
            name = "pistol_extendedclip",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "pistol_flashlight",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "pistol_suppressor",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "pistol_luxuryfinish",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "combatpistol_defaultclip",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "combatpistol_extendedclip",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "combatpistol_luxuryfinish",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "appistol_defaultclip",
            price = 300,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "appistol_extendedclip",
            price = 300,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "appistol_luxuryfinish",
            price = 300,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "pistol50_defaultclip",
            price = 300,
            amount = 50,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "pistol50_extendedclip",
            price = 300,
            amount = 50,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "revolver_defaultclip",
            price = 350,
            amount = 50,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "revolver_bodyguardvariant",
            price = 350,
            amount = 50,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "snspistol_defaultclip",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "snspistol_extendedclip",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "snspistol_grip",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "heavypistol_defaultclip",
            price = 300,
            amount = 50,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "heavypistol_extendedclip",
            price = 300,
            amount = 50,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "heavypistol_grip",
            price = 130000,
            amount = 50,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "vintagepistol_defaultclip",
            price = 300,
            amount = 50,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "vintagepistol_extendedclip",
            price = 300,
            amount = 50,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "microsmg_defaultclip",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 24,
        },
        [25] = {
            name = "microsmg_extendedclip",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 25,
        },
        [26] = {
            name = "microsmg_scope",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 26,
        },
        [27] = {
            name = "microsmg_luxuryfinish",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 27,
        },
        [28] = {
            name = "smg_defaultclip",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 28,
        },
        [29] = {
            name = "smg_extendedclip",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 29,
        },
        [30] = {
            name = "smg_drum",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 30,
        },
        [31] = {
            name = "smg_scope",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 31,
        },
        [32] = {
            name = "smg_luxuryfinish",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 32,
        },
        [33] = {
            name = "assaultsmg_defaultclip",
            price = 650,
            amount = 50,
            info = {},
            type = "item",
            slot = 33,
        },
        [34] = {
            name = "assaultsmg_extendedclip",
            price = 650,
            amount = 50,
            info = {},
            type = "item",
            slot = 34,
        },
        [35] = {
            name = "assaultsmg_luxuryfinish",
            price = 650,
            amount = 50,
            info = {},
            type = "item",
            slot = 35,
        },
        [36] = {
            name = "minismg_defaultclip",
            price = 650,
            amount = 50,
            info = {},
            type = "item",
            slot = 36,
        },
        [37] = {
            name = "minismg_extendedclip",
            price = 650,
            amount = 50,
            info = {},
            type = "item",
            slot = 37,
        },
        [38] = {
            name = "machinepistol_defaultclip",
            price = 650,
            amount = 50,
            info = {},
            type = "item",
            slot = 38,
        },
        [39] = {
            name = "machinepistol_extendedclip",
            price = 650,
            amount = 50,
            info = {},
            type = "item",
            slot = 39,
        },
        [40] = {
            name = "machinepistol_drum",
            price = 650,
            amount = 50,
            info = {},
            type = "item",
            slot = 40,
        },
        [41] = {
            name = "combatpdw_defaultclip",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 41,
        },
        [42] = {
            name = "combatpdw_extendedclip",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 42,
        },
        [43] = {
            name = "combatpdw_drum",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 43,
        },
        [44] = {
            name = "combatpdw_grip",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 44,
        },
        [45] = {
            name = "combatpdw_scope",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 45,
        },
        [46] = {
            name = "shotgun_suppressor",
            price = 350,
            amount = 50,
            info = {},
            type = "item",
            slot = 46,
        },
        [47] = {
            name = "pumpshotgun_luxuryfinish",
            price = 350,
            amount = 50,
            info = {},
            type = "item",
            slot = 47,
        },
        [48] = {
            name = "sawnoffshotgun_luxuryfinish",
            price = 350,
            amount = 50,
            info = {},
            type = "item",
            slot = 48,
        },
        [49] = {
            name = "assaultshotgun_defaultclip",
            price = 350,
            amount = 50,
            info = {},
            type = "item",
            slot = 49,
        },
        [50] = {
            name = "assaultshotgun_extendedclip",
            price = 350,
            amount = 50,
            info = {},
            type = "item",
            slot = 50,
        },
        [51] = {
            name = "heavyshotgun_defaultclip",
            price = 400,
            amount = 50,
            info = {},
            type = "item",
            slot = 51,
        },
        [52] = {
            name = "heavyshotgun_extendedclip",
            price = 400,
            amount = 50,
            info = {},
            type = "item",
            slot = 52,
        },
        [53] = {
            name = "heavyshotgun_drum",
            price = 400,
            amount = 50,
            info = {},
            type = "item",
            slot = 53,
        },
        [54] = {
            name = "assaultrifle_defaultclip",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 54,
        },
        [55] = {
            name = "assaultrifle_extendedclip",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 55,
        },
        [56] = {
            name = "assaultrifle_drum",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 56,
        },
        [57] = {
            name = "rifle_flashlight",
            price = 600,
            amount = 50,
            info = {},
            type = "item",
            slot = 57,
        },
        [58] = {
            name = "rifle_grip",
            price = 600,
            amount = 50,
            info = {},
            type = "item",
            slot = 58,
        },
        [59] = {
            name = "rifle_suppressor",
            price = 600,
            amount = 50,
            info = {},
            type = "item",
            slot = 59,
        },
        [60] = {
            name = "assaultrifle_luxuryfinish",
            price = 600,
            amount = 50,
            info = {},
            type = "item",
            slot = 60,
        },
        [61] = {
            name = "carbinerifle_defaultclip",
            price = 600,
            amount = 50,
            info = {},
            type = "item",
            slot = 61,
        },
        [62] = {
            name = "carbinerifle_extendedclip",
            price = 600,
            amount = 50,
            info = {},
            type = "item",
            slot = 62,
        },
        [63] = {
            name = "carbinerifle_drum",
            price = 600,
            amount = 50,
            info = {},
            type = "item",
            slot = 63,
        },
        [64] = {
            name = "carbinerifle_scope",
            price = 600,
            amount = 50,
            info = {},
            type = "item",
            slot = 64,
        },
        [65] = {
            name = "carbinerifle_luxuryfinish",
            price = 600,
            amount = 50,
            info = {},
            type = "item",
            slot = 65,
        },
        [66] = {
            name = "advancedrifle_defaultclip",
            price = 850,
            amount = 50,
            info = {},
            type = "item",
            slot = 66,
        },
        [67] = {
            name = "advancedrifle_extendedclip",
            price = 850,
            amount = 50,
            info = {},
            type = "item",
            slot = 67,
        },
        [68] = {
            name = "advancedrifle_luxuryfinish",
            price = 850,
            amount = 50,
            info = {},
            type = "item",
            slot = 68,
        },
        [69] = {
            name = "specialcarbine_defaultclip",
            price = 850,
            amount = 50,
            info = {},
            type = "item",
            slot = 69,
        },
        [70] = {
            name = "specialcarbine_extendedclip",
            price = 850,
            amount = 50,
            info = {},
            type = "item",
            slot = 70,
        },
        [71] = {
            name = "specialcarbine_drum",
            price = 850,
            amount = 50,
            info = {},
            type = "item",
            slot = 71,
        },
        [72] = {
            name = "specialcarbine_luxuryfinish",
            price = 850,
            amount = 50,
            info = {},
            type = "item",
            slot = 72,
        },
        [73] = {
            name = "bullpuprifle_defaultclip",
            price = 800,
            amount = 50,
            info = {},
            type = "item",
            slot = 73,
        },
        [74] = {
            name = "bullpuprifle_extendedclip",
            price = 800,
            amount = 50,
            info = {},
            type = "item",
            slot = 74,
        },
        [75] = {
            name = "bullpuprifle_luxuryfinish",
            price = 800,
            amount = 50,
            info = {},
            type = "item",
            slot = 75,
        },
        [76] = {
            name = "compactrifle_defaultclip",
            price = 18002,
            amount = 50,
            info = {},
            type = "item",
            slot = 76,
        },
        [77] = {
            name = "compactrifle_extendedclip",
            price = 800,
            amount = 50,
            info = {},
            type = "item",
            slot = 77,
        },
        [78] = {
            name = "compactrifle_drum",
            price = 800,
            amount = 50,
            info = {},
            type = "item",
            slot = 78,
        },
        [79] = {
            name = "gusenberg_defaultclip",
            price = 800,
            amount = 50,
            info = {},
            type = "item",
            slot = 79,
        },
        [80] = {
            name = "gusenberg_extendedclip",
            price = 800,
            amount = 50,
            info = {},
            type = "item",
            slot = 80,
        },
    },
    ["maindealer"] = {
        [1] = {
            name = "joint",
            price = 20,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "crack_baggy",
            price = 5,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "rolling_paper",
            price = 5,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "weed_white-widow",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "weed_skunk",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "weed_purple-haze",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "weed_og-kush",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "weed_amnesia",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "weed_ak47",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "weed_white-widow_seed",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "weed_skunk_seed",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "weed_purple-haze_seed",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "weed_og-kush_seed",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "weed_amnesia_seed",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "weed_ak47_seed",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "empty_weed_bag",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "weed_nutrition",
            price = 20,
            amount = 50,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "gatecrack",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "nitrous",
            price = 1000,
            amount = 50,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "tunerlaptop",
            price = 1000,
            amount = 50,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "painkillers",
            price = 25,
            amount = 50,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "radioscanner",
            price = 400,
            amount = 50,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "laptop",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "armor",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 24,
        },
        [25] = {
            name = "heavyarmor",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 25,
        },
        [26] = {
            name = "handcuffs",
            price = 25,
            amount = 50,
            info = {},
            type = "item",
            slot = 26,
        },
        [27] = {
            name = "lighter",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 27,
        },
        [28] = {
            name = "trojan_usb",
            price = 20,
            amount = 50,
            info = {},
            type = "item",
            slot = 28,
        },
        [29] = {
            name = "thermite",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 29,
        },
        [30] = {
            name = "security_card_01",
            price = 15,
            amount = 50,
            info = {},
            type = "item",
            slot = 30,
        },
        [31] = {
            name = "security_card_02",
            price = 15,
            amount = 50,
            info = {},
            type = "item",
            slot = 31,
        },
        [32] = {
            name = "weaponlicense",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 32,
        },
        [33] = {
            name = "advancedlockpick",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 33,
        },
        [34] = {
            name = "ifaks",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 34,
        },
        [35] = {
            name = "drill",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 35,
        },
    },
}

Config.Locations = {
    
    ["weapon"] = {
        ["label"] = "Weapon Dealer",   ---> You can change name
        ["coords"] = vector4(-66.08, -1239.35, 29.03, 53.48),  ---> You can change locations
        ["ped"] = 'mp_m_exarmy_01',   ---> https://docs.fivem.net/docs/game-references/ped-models/
        ["scenario"] = "WORLD_HUMAN_AA_SMOKE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Buy Weapons",
        ["products"] = Config.Products["weapon"],
        ["showblip"] = true,   ---> Make it false if you dont't want blips
        ["blipsprite"] = 150,     ---> https://docs.fivem.net/docs/game-references/blips/
        ["blipcolor"] = 11      ---> https://docs.fivem.net/docs/game-references/blips/
    },

    ["weaponattachments"] = {
        ["label"] = "Weapon Attachments Dealer",  ---> You can change name
        ["coords"] = vector4(-72.07, -1233.34, 29.01, 232.51),   ---> You can change locations
        ["ped"] = 'mp_m_waremech_01',    ---> https://docs.fivem.net/docs/game-references/ped-models/
        ["scenario"] = "WORLD_HUMAN_SMOKING_POT",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Buy Weapons Attachments",
        ["products"] = Config.Products["weaponattachments"],
        ["showblip"] = true,   ---> Make it false if you dont't want blips
        ["blipsprite"] = 155,     ---> https://docs.fivem.net/docs/game-references/blips/
        ["blipcolor"] = 11     ---> https://docs.fivem.net/docs/game-references/blips/
    },

    ["maindealer"] = {
        ["label"] = "Blackmarket Dealer",   ---> You can change name
        ["coords"] = vector4(-72.46, -1243.04, 29.11, 338.06),   ---> You can change locations
        ["ped"] = 'a_m_o_tramp_01',   ---> https://docs.fivem.net/docs/game-references/ped-models/
        ["scenario"] = "WORLD_HUMAN_DRUG_DEALER",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-cart-plus",
        ["targetLabel"] = "Buy Illegal Items",
        ["products"] = Config.Products["maindealer"],
        ["showblip"] = true,   ---> Make it false if you dont't want blips
        ["blipsprite"] = 480,    ---> https://docs.fivem.net/docs/game-references/blips/
        ["blipcolor"] = 11      ---> https://docs.fivem.net/docs/game-references/blips/
    },
}
